name: CI Synthesize
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker build -t kokoro_tts .
          docker run --name kokoro_tts -v ${{ github.workspace }}/output:/app/output \
            -v ${{ github.workspace }}/synthesize.py:/app/synthesize.py \
            -v ${{ github.workspace }}/1-teste.txt:/app/1-teste.txt \
            -v ${{ github.workspace }}/2-teste.txt:/app/2-teste.txt \
            kokoro_tts sh -c "python synthesize.py 1-teste.txt"

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: synthesized-output
          path: output/
